---
abstract: 'Create an archive of TAP test results'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TAP-Harness-Archive
provides:
  TAP::Harness::Archive:
    file: lib/TAP/Harness/Archive.pm
    version: 0.15
requires:
  Archive::Tar: 0
  Cwd: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0.19
  TAP::Harness: 3.05
  Test::More: 0
  YAML::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
